//
//  DeveloperPreview.swift
//  airbnb
//
//  Created by Gizem Candemir on 7/17/25.
//

import Foundation

class DeveloperPreview{
    static let shared = DeveloperPreview()
    
    let listings: [Listing] = [
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Gizem Candemir",
            ownerImageUrl: "gizem",
            numberOfBedrooms: 2,
            numberofBathrooms: 2,
            numberOfGuests: 1,
            pricePerNight: 567,
            latitude: 25.7850,
            longitude: -80.1936,
            address: "12345 Main Street",
            city: "Miami",
            state:"Florida",
            title:"Miami Villa",
            rating: 4.86,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi , .balcony, .alarmSystem, .laundry, .tv],
            type: .villa,
            imageUrls: ["listing-1", "listing-2", "listing-3"]
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Ahmet Yılmaz",
            ownerImageUrl: "gizem",
            numberOfBedrooms: 3,
            numberofBathrooms: 2,
            numberOfGuests: 4,
            pricePerNight: 820,
            latitude: 41.0082,
            longitude: 28.9784,
            address: "456 Sunset Blvd",
            city: "Istanbul",
            state:"Sariyer",
            title:"Modern LA Retreat",
            rating: 4.9,
            features: [.superHost],
            amenities: [.wifi, .pool, .tv, .kitchen],
            type: .apartment,
            imageUrls: ["listing-4", "listing-2", "listing-3"]
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Elif Kaya",
            ownerImageUrl: "elif",
            numberOfBedrooms: 1,
            numberofBathrooms: 1,
            numberOfGuests: 2,
            pricePerNight: 320,
            latitude: 40.7128,
            longitude: -74.0060,
            address: "789 Broadway",
            city: "New York",
            state:"New York",
            title:"Cozy Manhattan Studio",
            rating: 4.5,
            features: [.selfCheckIn],
            amenities: [.wifi, .laundry, .kitchen],
            type: .apartment,
            imageUrls: ["listing-5", "listing-2", "listing-3"]
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "John Doe",
            ownerImageUrl: "gizem",
            numberOfBedrooms: 5,
            numberofBathrooms: 4,
            numberOfGuests: 10,
            pricePerNight: 1200,
            latitude: 36.1699,
            longitude: -115.1398,
            address: "654 Vegas Strip",
            city: "Las Vegas",
            state:"Nevada",
            title:"Luxury Vegas Mansion",
            rating: 4.8,
            features: [.superHost, .selfCheckIn],
            amenities: [.wifi, .pool, .tv],
            type: .villa,
            imageUrls: ["listing-2", "listing-2", "listing-3"]
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Mehmet Demir",
            ownerImageUrl: "gizem",
            numberOfBedrooms: 2,
            numberofBathrooms: 1,
            numberOfGuests: 3,
            pricePerNight: 430,
            latitude: 41.8781,
            longitude: -87.6298,
            address: "321 Lakeshore Drive",
            city: "Chicago",
            state:"Illinois",
            title:"Chic Chicago Loft",
            rating: 4.6,
            features: [],
            amenities: [.wifi, .laundry, .tv],
            type: .apartment,
            imageUrls: ["listing-3", "listing-2", "listing-3"]
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Zeynep Arslan",
            ownerImageUrl: "gizem",
            numberOfBedrooms: 4,
            numberofBathrooms: 3,
            numberOfGuests: 6,
            pricePerNight: 750,
            latitude: 47.6062,
            longitude: -122.3321,
            address: "987 Rainy Ave",
            city: "Seattle",
            state:"Washington",
            title:"Peaceful Seattle Home",
            rating: 4.4,
            features: [.selfCheckIn],
            amenities: [.wifi, .balcony, .laundry],
            type: .house,
            imageUrls: ["listing-1", "listing-2", "listing-3"]
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Can Aydın",
            ownerImageUrl: "gizem",
            numberOfBedrooms: 1,
            numberofBathrooms: 1,
            numberOfGuests: 1,
            pricePerNight: 280,
            latitude: 39.7392,
            longitude: -104.9903,
            address: "1350 Downtown",
            city: "Denver",
            state:"Colorado",
            title:"Minimalist Downtown Pad",
            rating: 4.2,
            features: [],
            amenities: [.wifi, .tv],
            type: .townHouse,
            imageUrls: ["listing-1", "listing-2", "listing-3"]
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Ayşe Kaplan",
            ownerImageUrl: "gizem",
            numberOfBedrooms: 3,
            numberofBathrooms: 2,
            numberOfGuests: 5,
            pricePerNight: 590,
            latitude: 32.7157,
            longitude: -117.1611,
            address: "678 Ocean Blvd",
            city: "San Diego",
            state:"California",
            title:"Beachside Bungalow",
            rating: 4.7,
            features: [.superHost],
            amenities: [.wifi, .balcony, .tv, .kitchen],
            type: .house,
            imageUrls: ["listing-1", "listing-2", "listing-3"]
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Ali Tuncer",
            ownerImageUrl: "gizem",
            numberOfBedrooms: 2,
            numberofBathrooms: 2,
            numberOfGuests: 4,
            pricePerNight: 610,
            latitude: 29.7604,
            longitude: -95.3698,
            address: "432 Bayou Street",
            city: "Houston",
            state:"Texas",
            title:"Urban Oasis Houston",
            rating: 4.3,
            features: [],
            amenities: [.wifi, .laundry, .tv],
            type: .apartment,
            imageUrls: ["listing-1", "listing-2", "listing-3"]
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Buse Aksoy",
            ownerImageUrl: "buse",
            numberOfBedrooms: 3,
            numberofBathrooms: 3,
            numberOfGuests: 6,
            pricePerNight: 880,
            latitude: 33.4484,
            longitude: -112.0740,
            address: "910 Desert Rd",
            city: "Phoenix",
            state:"Arizona",
            title:"Desert Dream Home",
            rating: 4.9,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .pool, .tv, .laundry],
            type: .villa,
            imageUrls: ["listing-1", "listing-2", "listing-3"]
            
        )
    ]
}
